spring:
  application:
    name: MusicStore

---

spring:
  config:
    activate:
      on-profile: dev

  datasource:
    generate-unique-name: false
    #url: jdbc:h2:file:./h2-file/warehouse-dev
    url: jdbc:h2:mem:store-dev
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update

  sql:
    init:
      mode: always
      schema-locations: classpath:db/schema.sql
      data-locations: classpath:db/data.sql

server:
  port: 8080

---

spring:
  config:
    activate:
      on-profile: test

  datasource:
    generate-unique-name: false
    url: jdbc:h2:file:./h2-file/store-test
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update

  sql:
    init:
      mode: always
      schema-locations: classpath:db/schema.sql
      data-locations: classpath:db/data.sql

server:
  port: 8088