CREATE SEQUENCE IF NOT EXISTS warehouse_seq START WITH 1 INCREMENT BY 1;
CREATE TABLE IF NOT EXISTS items (
    id BIGINT PRIMARY KEY,
    code VARCHAR(6) NOT NULL,
    type VARCHAR(50) NOT NULL,
    name VARCHAR(50) NOT NULL,
    price DECIMAL(10,2) NOT NULL,
    itemCount INT NOT NULL
);


