CREATE SEQUENCE IF NOT EXISTS store_seq START WITH 1 INCREMENT BY 1;
CREATE TABLE IF NOT EXISTS instrument (
    id BIGINT PRIMARY KEY,
    type VARCHAR(50) NOT NULL,
    brand VARCHAR(50) NOT NULL,
    model VARCHAR(50) NOT NULL,
    price DECIMAL(10,2) NOT NULL,
    stock INT NOT NULL
);


